// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSoftware.DataAccess;

#nullable disable

namespace ProyectoSoftware.Migrations
{
    [DbContext(typeof(RevisionTecnicaContext))]
    [Migration("20260628155504_SeedGerente")]
    partial class SeedGerente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoSoftware.Models.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividad"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCulminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdIngenieroAsignado")
                        .HasColumnType("int");

                    b.Property<string>("IdProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NombreActividad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdActividad");

                    b.HasIndex("IdIngenieroAsignado");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Proyecto", b =>
                {
                    b.Property<string>("IdProyecto")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProyecto");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Revision", b =>
                {
                    b.Property<int>("IdRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRevision"));

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActividad")
                        .HasColumnType("int");

                    b.Property<int>("IdIngenieroRevisor")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Veredicto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdRevision");

                    b.HasIndex("IdActividad");

                    b.HasIndex("IdIngenieroRevisor");

                    b.ToTable("Revisiones");
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Email = "gerente@sistema.com",
                            Nombre = "Gerente Principal",
                            Password = "123",
                            Rol = "Gerencia"
                        });
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Actividad", b =>
                {
                    b.HasOne("ProyectoSoftware.Models.Usuario", "IngenieroAsignado")
                        .WithMany("ActividadesAsignadas")
                        .HasForeignKey("IdIngenieroAsignado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoSoftware.Models.Proyecto", "Proyecto")
                        .WithMany("Actividades")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngenieroAsignado");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Revision", b =>
                {
                    b.HasOne("ProyectoSoftware.Models.Actividad", "Actividad")
                        .WithMany("Revisiones")
                        .HasForeignKey("IdActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoSoftware.Models.Usuario", "IngenieroRevisor")
                        .WithMany("RevisionesAsignadas")
                        .HasForeignKey("IdIngenieroRevisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("IngenieroRevisor");
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Actividad", b =>
                {
                    b.Navigation("Revisiones");
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Proyecto", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("ProyectoSoftware.Models.Usuario", b =>
                {
                    b.Navigation("ActividadesAsignadas");

                    b.Navigation("RevisionesAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
